import { useState } from 'react'
import { Link, NavLink } from 'react-router-dom'
import { Menu, X, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { ThemeToggle } from '@/components/ui/theme-toggle'
import { useAuth } from '@/auth/AuthProvider'

const links = [['Marketplace', '#marketplace'], ['Solutions', '#features'], ['Developers', '#developers'], ['Resources', '#resources'], ['Pricing', '#pricing']]
export function Logo() { return <Link to="/" className="flex items-center gap-2.5 text-lg font-extrabold tracking-tight text-slate-950 dark:text-white"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#3455db] text-white shadow-lg shadow-blue-500/20"><Sparkles size={17} fill="currentColor" /></span>AgentHub</Link> }
export function Navbar() {
  const [open, setOpen] = useState(false); const { user, signOut } = useAuth()
  return <header className="sticky top-0 z-50 border-b border-slate-200/70 bg-[#f7f8fb]/85 backdrop-blur-xl dark:border-slate-800/80 dark:bg-[#080d18]/85"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-7 lg:flex">{links.map(([label, href]) => <a key={label} href={href} className="text-sm font-semibold text-slate-500 transition hover:text-slate-950 dark:text-slate-400 dark:hover:text-white">{label}</a>)}</nav><div className="hidden items-center gap-2 lg:flex"><ThemeToggle />{user ? <><NavLink to="/profile"><Button variant="ghost" size="sm">Profile</Button></NavLink><Button variant="outline" size="sm" onClick={signOut}>Log out</Button></> : <><NavLink to="/login"><Button variant="ghost" size="sm">Sign in</Button></NavLink><NavLink to="/register"><Button size="sm">Get started <span aria-hidden>↗</span></Button></NavLink></>}</div><div className="flex items-center gap-1 lg:hidden"><ThemeToggle /><Button variant="ghost" size="icon" aria-label={open ? 'Close navigation menu' : 'Open navigation menu'} onClick={() => setOpen(value => !value)}>{open ? <X size={20} /> : <Menu size={20} />}</Button></div></div>{open && <div className="border-t border-slate-200/70 bg-[#f7f8fb] px-5 py-5 dark:border-slate-800 dark:bg-[#080d18] lg:hidden"><nav className="flex flex-col gap-1">{links.map(([label, href]) => <a key={label} href={href} onClick={() => setOpen(false)} className="rounded-xl px-3 py-3 text-sm font-semibold text-slate-600 hover:bg-white dark:text-slate-300 dark:hover:bg-slate-900">{label}</a>)}</nav><div className="mt-4 grid grid-cols-2 gap-2 border-t border-slate-200 pt-4 dark:border-slate-800"><NavLink to={user ? '/profile' : '/login'} onClick={() => setOpen(false)}><Button variant="outline" className="w-full">{user ? 'Profile' : 'Sign in'}</Button></NavLink>{user ? <Button onClick={() => { setOpen(false); signOut() }} variant="secondary" className="w-full">Log out</Button> : <NavLink to="/register" onClick={() => setOpen(false)}><Button className="w-full">Get started</Button></NavLink>}</div></div>}</header>
}
