import { useState } from 'react'
import { Link, NavLink } from 'react-router-dom'
import { Boxes, ChevronRight, Database, GitBranch, Home, KeyRound, LogOut, Menu, Network, Settings2, Sparkles, UserRound, X } from 'lucide-react'
import { useAuth } from '@/auth/AuthProvider'
import { Button } from '@/components/ui/button'
import { ThemeToggle } from '@/components/ui/theme-toggle'
import { cn } from '@/lib/utils'

const navItems = [{ label: 'Home', href: '/home', icon: Home }, { label: 'Agents', href: '/agents', icon: Sparkles }, { label: 'MCP servers', href: '/mcp-servers', icon: Network }, { label: 'LLM providers', href: '/llm-settings', icon: Settings2 }, { label: 'Workflows', href: '/home#workflows', icon: GitBranch, staged: true }, { label: 'Knowledge bases', href: '/home#knowledge', icon: Database, staged: true }]

function Sidebar({ onNavigate }: { onNavigate?: () => void }) { const { user, signOut } = useAuth(); return <aside className="flex h-full w-64 flex-col border-r border-slate-200 bg-white px-4 py-5 dark:border-slate-800 dark:bg-slate-950"><Link to="/home" className="flex items-center gap-2.5 px-3 text-lg font-extrabold tracking-tight text-slate-950 dark:text-white"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#3455db] text-white"><Sparkles size={17} fill="currentColor" /></span>AgentHub</Link><p className="mb-3 mt-10 px-3 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Workspace</p><nav className="space-y-1">{navItems.map(item => <NavLink key={item.label} to={item.href} onClick={onNavigate} className={({ isActive }) => cn('flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition', isActive && !item.staged ? 'bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300' : 'text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800')}><item.icon size={17} /><span className="flex-1">{item.label}</span>{item.staged ? <span className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Soon</span> : <ChevronRight size={14} className="opacity-40" />}</NavLink>)}</nav><div className="mt-auto space-y-1 border-t border-slate-100 pt-4 dark:border-slate-800"><NavLink to="/profile" onClick={onNavigate} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"><UserRound size={17} />Profile</NavLink><NavLink to="/update-password" onClick={onNavigate} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"><KeyRound size={17} />Password</NavLink><button onClick={signOut} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold text-rose-600 hover:bg-rose-50 dark:text-rose-400 dark:hover:bg-rose-500/10"><LogOut size={17} />Log out</button><p className="truncate px-3 pt-3 text-xs text-slate-400">{user?.email}</p></div></aside> }
export function WorkspaceLayout({ children }: { children: React.ReactNode }) { const [open, setOpen] = useState(false); return <div className="min-h-screen bg-[#f7f8fb] dark:bg-[#080d18]"><header className="flex h-[72px] items-center justify-between border-b border-slate-200 bg-white px-5 dark:border-slate-800 dark:bg-slate-950 lg:hidden"><Link to="/home" className="flex items-center gap-2 font-extrabold text-slate-950 dark:text-white"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#3455db] text-white"><Sparkles size={16} fill="currentColor" /></span>AgentHub</Link><div className="flex items-center gap-1"><ThemeToggle /><Button variant="ghost" size="icon" aria-label="Toggle workspace navigation" onClick={() => setOpen(value => !value)}>{open ? <X size={19} /> : <Menu size={19} />}</Button></div></header><div className="flex min-h-[calc(100vh-72px)] lg:min-h-screen"><div className="hidden lg:block"><Sidebar /></div>{open && <div className="fixed inset-0 z-50 flex lg:hidden"><button className="absolute inset-0 bg-slate-950/30" aria-label="Close navigation" onClick={() => setOpen(false)} /><div className="relative"><Sidebar onNavigate={() => setOpen(false)} /></div></div>}<div className="min-w-0 flex-1"><div className="hidden justify-end border-b border-slate-200 px-8 py-4 dark:border-slate-800 lg:flex"><ThemeToggle /></div>{children}</div></div></div> }