import { Link, useLocation } from 'react-router-dom'
import { KeyRound, LogOut, UserRound } from 'lucide-react'
import { useAuth } from '@/auth/AuthProvider'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'

export function AccountNav() {
  const { user, signOut } = useAuth(); const location = useLocation()
  return <aside className="space-y-6"><div className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-700 dark:bg-blue-500/15 dark:text-blue-300">{user?.name.slice(0, 2).toUpperCase()}</div><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-950 dark:text-white">{user?.name}</p><p className="truncate text-xs text-slate-500 dark:text-slate-400">{user?.email}</p></div></div><div className="mt-5 rounded-xl bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-500 dark:bg-slate-800 dark:text-slate-400">{user?.role} account</div></div><nav className="space-y-1"><Link to="/profile" className={cn('flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition', location.pathname === '/profile' ? 'bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300' : 'text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800')}><UserRound size={17} />Profile</Link><Link to="/update-password" className={cn('flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition', location.pathname === '/update-password' ? 'bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300' : 'text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800')}><KeyRound size={17} />Update password</Link></nav><Button type="button" variant="ghost" className="w-full justify-start text-rose-600 hover:bg-rose-50 hover:text-rose-700 dark:text-rose-400 dark:hover:bg-rose-500/10" onClick={signOut}><LogOut size={17} />Log out</Button></aside>
}