import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { AlertCircle, Check, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { PasswordInput } from '@/components/ui/password-input'
import { SocialLoginButton } from './SocialLoginButton'
import { useToast } from '@/components/ui/toast'
import { register } from '@/lib/api'
import { useAuth } from '@/auth/AuthProvider'

function Label({ children, htmlFor }: { children: React.ReactNode; htmlFor: string }) { return <label htmlFor={htmlFor} className="mb-2 block text-sm font-bold text-slate-800 dark:text-slate-200">{children}</label> }
function SubmitButton({ children, loading }: { children: React.ReactNode; loading: boolean }) { return <Button type="submit" size="lg" className="w-full">{loading ? <><Loader2 size={17} className="animate-spin" />Working...</> : children}</Button> }

export function LoginForm() {
  const { show } = useToast(); const { signIn } = useAuth(); const navigate = useNavigate(); const [loading, setLoading] = useState(false)
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); try { await signIn(String(form.get('email')), String(form.get('password'))); show('Signed in', 'Your AgentHub workspace is ready.'); navigate('/home') } catch (error) { show('Sign in failed', error instanceof Error ? error.message : 'Unable to sign in.') } finally { setLoading(false) } }
  return <form onSubmit={submit} className="space-y-5"><div><Label htmlFor="email">Email address</Label><Input id="email" name="email" type="email" placeholder="you@company.com" required autoComplete="email" /></div><div><div className="flex items-center justify-between"><Label htmlFor="password">Password</Label><Link to="/forgot-password" className="text-xs font-bold text-blue-600 hover:text-blue-700 dark:text-blue-400">Forgot password?</Link></div><PasswordInput id="password" name="password" placeholder="Enter your password" required autoComplete="current-password" /></div><label className="flex cursor-pointer items-center gap-3 text-sm text-slate-500 dark:text-slate-400"><Checkbox id="remember" />Remember me</label><SubmitButton loading={loading}>Sign in <span aria-hidden>↗</span></SubmitButton><div className="relative py-1 text-center text-[11px] font-bold uppercase tracking-[.16em] text-slate-400"><span className="relative z-10 bg-[#f7f8fb] px-3 dark:bg-[#080d18]">Or continue with</span><span className="absolute left-0 top-1/2 w-full border-t border-slate-200 dark:border-slate-800" /></div><SocialLoginButton label="Continue with Google" /><p className="pt-2 text-center text-sm text-slate-500 dark:text-slate-400">Don't have an account? <Link to="/register" className="font-bold text-blue-600 hover:text-blue-700 dark:text-blue-400">Create account</Link></p></form>
}

export function RegisterForm() {
  const { show } = useToast(); const [loading, setLoading] = useState(false); const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [agreed, setAgreed] = useState(false)
  const strength = password.length >= 10 && /[A-Z]/.test(password) && /\d/.test(password) ? 'Strong' : password.length >= 6 ? 'Medium' : 'Weak'
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (password !== confirmation) return show('Passwords do not match', 'Enter the same password in both fields.'); if (!agreed) return show('Terms required', 'Please agree to the Terms of Service and Privacy Policy.'); const form = new FormData(event.currentTarget); setLoading(true); try { await register(String(form.get('full-name')), String(form.get('register-email')), password); show('Account created', 'You can now sign in to AgentHub.') } catch (error) { show('Registration failed', error instanceof Error ? error.message : 'Unable to create your account.') } finally { setLoading(false) } }
  return <form onSubmit={submit} className="space-y-4"><div><Label htmlFor="full-name">Full name</Label><Input id="full-name" name="full-name" placeholder="Alex Morgan" required autoComplete="name" /></div><div><Label htmlFor="register-email">Work email</Label><Input id="register-email" name="register-email" type="email" placeholder="you@company.com" required autoComplete="email" /></div><div><Label htmlFor="register-password">Password</Label><PasswordInput id="register-password" name="register-password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Create a secure password" required autoComplete="new-password" /><div className="mt-3 flex items-center gap-3"><span className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800"><span className={`block h-full rounded-full transition-all ${strength === 'Strong' ? 'w-full bg-emerald-500' : strength === 'Medium' ? 'w-2/3 bg-amber-500' : password ? 'w-1/3 bg-rose-500' : 'w-0'}`} /></span><span className="w-12 text-right text-[11px] font-bold text-slate-500">{password ? strength : ''}</span></div></div><div><Label htmlFor="confirm-password">Confirm password</Label><PasswordInput id="confirm-password" name="confirm-password" value={confirmation} onChange={event => setConfirmation(event.target.value)} placeholder="Repeat your password" required autoComplete="new-password" /></div><label className="flex cursor-pointer items-start gap-3 py-1 text-xs leading-5 text-slate-500 dark:text-slate-400"><Checkbox checked={agreed} onChange={event => setAgreed(event.target.checked)} /> <span>I agree to the <a href="#" className="font-bold text-slate-700 underline dark:text-slate-200">Terms of Service</a> and <a href="#" className="font-bold text-slate-700 underline dark:text-slate-200">Privacy Policy</a>.</span></label><SubmitButton loading={loading}>Create account <span aria-hidden>↗</span></SubmitButton><SocialLoginButton /><p className="pt-2 text-center text-sm text-slate-500 dark:text-slate-400">Already have an account? <Link to="/login" className="font-bold text-blue-600 hover:text-blue-700 dark:text-blue-400">Sign in</Link></p></form>
}

export function ForgotPasswordForm() { const { show } = useToast(); const [sent, setSent] = useState(false); const submit = (event: React.FormEvent) => { event.preventDefault(); setSent(true); show('Check your email', 'Password reset is not available in the current FastAPI backend.') }; if (sent) return <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 dark:border-emerald-500/30 dark:bg-emerald-500/10"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-emerald-500 text-white"><Check size={21} /></div><h3 className="mt-5 text-lg font-bold text-slate-950 dark:text-white">Request received</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Password reset will be connected when the backend endpoint is added.</p><Link to="/login" className="mt-5 inline-flex text-sm font-bold text-emerald-700 dark:text-emerald-300">Back to sign in <span className="ml-1">↗</span></Link></div>; return <form onSubmit={submit} className="space-y-5"><div><Label htmlFor="reset-email">Email address</Label><Input id="reset-email" type="email" placeholder="you@company.com" required autoComplete="email" /></div><Button type="submit" size="lg" className="w-full">Send reset link <span aria-hidden>↗</span></Button><div className="flex items-center justify-center gap-2 pt-2 text-xs text-slate-400"><AlertCircle size={14} /> Reset endpoint not available yet.</div><p className="pt-2 text-center text-sm text-slate-500 dark:text-slate-400"><Link to="/login" className="font-bold text-blue-600 hover:text-blue-700 dark:text-blue-400">Back to sign in</Link></p></form> }
